#web server
server:
  port: 8080
  servlet:
    context-path: /app
  tomcat:
    uri-encoding: UTF-8

spring:
  #time format
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #datasource
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/user?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&useAffectedRows=true
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
    #连接池建立时创建的初始化连接数
    initialSize: 5
    #连接池中最小连接数
    minIdle: 5
    #连接池中最大连接数
    maxActive: 20
    #获取连接时最大等待时间，单位是毫秒
    maxWait: 60000
    #间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    #一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    #用来检测连接是否有效
    validationQuery: SELECT 1
    #是否在连接空闲一段时间后检测其可用性，申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效
    testWhileIdle: true
    #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnBorrow: false
    #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    testOnReturn: false
    #是否缓存preparedStatement，也就是PSCache
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    useGlobalDataSourceStat: true

#mybatis
mybatis:
   configuration:
      mapUnderscoreToCamelCase: true
   mapperLocations: classpath:mapper/*.xml
   typeAliasesPackage: com.wuwei.entity